# For more information: https://laravel.com/docs/sail
version: '3'
services:
  my_mssql:
    container_name: my_mssql
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: $DB_PASSWORD
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
    volumes:
      - "./data/mssql/backup:/var/opt/mssql/backup"
      - "./data/mssql/db:/var/opt/mssql/data"
networks:
  mynet:
     external: true